name: mcp-network

services:
  mcp-rag-server:
    image: ghcr.io/rwuniard/mcp_rag:latest
    container_name: mcp-rag-server
    ports:
      - "8080:8080"
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8080
      - MCP_TRANSPORT=http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp-network
    external: true